openapi: 3.0.0
info:
  title: Ultistat API
  description: Documentation for the Ultistats API.
  version: 0.1.9
servers:
  - url: http://localhost:3000/
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
tags:
  - name: Teams
  - name: Games

paths:
  /teams:
    get:
      summary: Returns a user by ID.
      tags:
        - Teams
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  teams_id:
                    type: string
                  teams_name:
                    type: string
                  team_player_number:
                    type: integer

  /teams/{teams_id}:
    get:
      summary: Returns a user by ID.
      tags:
        - Teams
      parameters:
        - in: path
          name: teams_id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  teams_id:
                    type: string
                  teams_name:
                    type: string
                  team_player_number:
                    type: integer

        '400':
          description: The specified user ID is invalid (not a number).
        '404':
          description: A user with the specified ID was not found.
        default:
          description: Unexpected error

  /addteams:
    post:
      summary: Creates a team.
      tags:
        - Teams
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                teams_name:
                  type: string
                team_player_number:
                  type: integer
      responses:
        '201':
          description: Created
        '400':
          description: The specified user ID is invalid (not a number).
        '404':
          description: A user with the specified ID was not found.
        default:
          description: Unexpected error

  /deleteteams/{teams_id}:
    delete:
      summary: Returns a user by ID.
      tags:
        - Teams
      parameters:
        - in: path
          name: teams_id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Team deleted.
        '400':
          description: The specified user ID is invalid (not a number).
        '404':
          description: A user with the specified ID was not found.
        default:
          description: Unexpected error

  /updateteams/{teams_id}:
    put:
      summary: Returns a user by ID.
      tags:
        - Teams
      parameters:
        - in: path
          name: teams_id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  teams_id:
                    type: string
                  teams_name:
                    type: string
                  team_player_number:
                    type: integer

        '400':
          description: The specified user ID is invalid (not a number).
        '404':
          description: A user with the specified ID was not found.
        default:
          description: Unexpected error

  /games:
    get:
      summary: Returns a user by ID.
      tags:
        - Games
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  teams_id:
                    type: string
                  teams_name:
                    type: string
                  team_player_number:
                    type: integer

  /games/{game_id}:
    get:
      summary: Returns a user by ID.
      tags:
        - Games
      parameters:
        - in: path
          name: game_id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  teams_id:
                    type: string
                  teams_name:
                    type: string
                  team_player_number:
                    type: integer

        '400':
          description: The specified user ID is invalid (not a number).
        '404':
          description: A user with the specified ID was not found.
        default:
          description: Unexpected error

  /addgames:
    post:
      summary: Creates a team.
      tags:
        - Games
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                game_point_number:
                  type: integer
                tournament:
                  type: string
                wind:
                  type: string
                surface:
                  type: string
                teams_name:
                  type: string
                game_date:
                  type: string
                point_1_team:
                  type: integer
                point_2_team:
                  type: integer
                point_3_team:
                  type: integer
                point_4_team:
                  type: integer
                point_5_team:
                  type: integer
                point_6_team:
                  type: integer
                point_7_team:
                  type: integer
                point_8_team:
                  type: integer
                point_9_team:
                  type: integer
                point_10_team:
                  type: integer
                point_11_team:
                  type: integer
                point_12_team:
                  type: integer
                point_13_team:
                  type: integer
                point_14_team:
                  type: integer
                point_15_team:
                  type: integer
                total_score_team_:
                  type: integer
      responses:
        '201':
          description: Created
        '400':
          description: The specified user ID is invalid (not a number).
        '404':
          description: A user with the specified ID was not found.
        default:
          description: Unexpected error

  /deletegames/{game_id}:
    delete:
      summary: Returns a user by ID.
      tags:
        - Games
      parameters:
        - in: path
          name: game_id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Team deleted.
        '400':
          description: The specified user ID is invalid (not a number).
        '404':
          description: A user with the specified ID was not found.
        default:
          description: Unexpected error

  /updategames/{game_id}:
    put:
      summary: Returns a user by ID.
      tags:
        - Games
      parameters:
        - in: path
          name: game_id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  teams_id:
                    type: string
                  teams_name:
                    type: string
                  team_player_number:
                    type: integer

        '400':
          description: The specified user ID is invalid (not a number).
        '404':
          description: A user with the specified ID was not found.
        default:
          description: Unexpected error
