DROP TABLE IF EXISTS games CASCADE;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE games (
    game_id uuid DEFAULT uuid_generate_v4(),
    play_id uuid REFERENCES plays (play_id),
	teams_id uuid REFERENCES teams (teams_id),
    game_point_number INT,
    tournament VARCHAR,
    wind VARCHAR,
    surface VARCHAR,
	teams_name VARCHAR,
	point_1_team INT,
    point_2_team INT,
    point_3_team INT,
    point_4_team INT,
    point_5_team INT,
    point_6_team INT,
    point_7_team INT,
    point_8_team INT,
    point_9_team INT,
    point_10_team INT,
    point_11_team INT,
    point_12_team INT,
    point_13_team INT,
    point_14_team INT,
    point_15_team INT,
    point_16_team INT,
    point_17_team INT,
    total_score_team_ INT,
	PRIMARY KEY (game_id));